
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
# gfcli:
#   docker:
#     build: "-a amd64 -s linux -p temp -ew"
#     tagPrefixes:
#       - my.image.pub/my-app

gfcli:
  gen:
    dao:
    - link:     "mysql:root:lingmysql@tcp(175.178.90.203:3306)/okgonav"
      tables:   "user,title,content"
      jsonCase: "CamelLower"

    - link:   "mysql:root:lingmysql@tcp(175.178.90.203:3306)/okgonav"
      path:   "./my-app"
      prefix: "primary_"
      tables: "user, userDetail"