// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"okgopro/internal/dao/internal"
)

// internalContentDao is internal type for wrapping internal DAO implements.
type internalContentDao = *internal.ContentDao

// contentDao is the data access object for table content.
// You can define custom methods on it to extend its functionality as you wish.
type contentDao struct {
	internalContentDao
}

var (
	// Content is globally public accessible object for table content operations.
	Content = contentDao{
		internal.NewContentDao(),
	}
)

// Fill with you ideas below.
