// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"okgopro/internal/dao/internal"
)

// internalTitleUrlDao is internal type for wrapping internal DAO implements.
type internalTitleUrlDao = *internal.TitleUrlDao

// titleUrlDao is the data access object for table title_url.
// You can define custom methods on it to extend its functionality as you wish.
type titleUrlDao struct {
	internalTitleUrlDao
}

var (
	// TitleUrl is globally public accessible object for table title_url operations.
	TitleUrl = titleUrlDao{
		internal.NewTitleUrlDao(),
	}
)

// Fill with you ideas below.
